Repository DSM-Today/DataSet, pull requests merged in 2022-09, with the labels that each got.

#2 🔀 :: (#1) 프로젝트 세팅
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
Labels: settings

#5 🔀 :: (#3) 패키지 구조 세팅
  cralwer/information/news.py
  cralwer/opertaion/book.py
  cralwer/opertaion/cafe/diser_39.py
  cralwer/opertaion/cafe/gong_cha.py
  cralwer/opertaion/cafe/juicy.py
  cralwer/opertaion/cafe/starbucks.py
  cralwer/opertaion/cafe/two_some.py
  cralwer/opertaion/food.py
  cralwer/opertaion/gift.py
  cralwer/opertaion/movie/cgv.py
  cralwer/opertaion/movie/megabox.py
  cralwer/opertaion/music.py
  cralwer/opertaion/vacation.py
  cralwer/opertaion/webtoon.py
  cralwer/random/flower.py
  cralwer/random/lion_word.py
  cralwer/random/lucky.py
  cralwer/random/quiz.py
  exception.md
Labels: settings

#8 🔀 :: (#6) 네이버 웹툰 크롤링
  cralwer/opertaion/webtoon.py
Labels: service

#11 🔀 :: 휴재 조건 설정 변경
  cralwer/opertaion/webtoon.py
Labels: chore

#12 🔀 :: (#7) News 크롤링
  cralwer/information/news.py
Labels: service
